DELETE http://localhost:3003/api/blogs/67b3249a3226dbd42066cd87
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpZ2VyIiwiaWQiOiI2N2EzNGQxNGZhMmRkNmM4MTRmYTg1Y2UiLCJpYXQiOjE3NDI3NTYwNTR9.OIyLklFo01RQ9lONF9Z01jsCNVcrmthb9T84cXTHf-0
